# project basic config
spring.application:
  name: pooi-workflow-core

server:
  port: 8080

# datasource
spring.datasource.dynamic:
  primary: core
  strict: true
  datasource:
    core:
      url: jdbc:h2:mem:pooi-workflow-core;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password:
      init:
        schema: classpath*:sql/init.sql
        data: classpath*:sql/data.sql
# redis
spring.redis:
  host: redis.pooi.app
  port: 6379

# discover
spring.cloud.consul:
  host: consul.pooi.app
  port: 443
  scheme: https
  discovery:
    enabled: true
    instanceId: ${spring.application.name}:${random.value} # ${spring.application.name}:${profiles separated by comma}:${server.port}”
    prefer-ip-address: true
    # healthCheckPath: /my-health-check
    healthCheckInterval: 10s
    tags:
      - "prometheus"
    metadata:
      prometheus-path: /actuator/prometheus # prometheus discovery exporter endpoint

# executor
spring.dynamic.tp:
  enabled: true
  enabledBanner: false
  enabledCollect: false
  collectorTypes: micrometer
  monitorInterval: 10
  executors:
    - threadPoolName: event-push
      executorType: common
      corePoolSize: 20
      maximumPoolSize: 20
      rejectedHandlerType: CallerRunsPolicy
      keepAliveTime: 120
      threadNamePrefix: dtp-event-push
      awaitTerminationSeconds: 10
      taskWrapperNames: ["ttl", "mdc", "swTrace"]
      notifyEnabled: false
management:
  endpoints:
    web.exposure:
      include: prometheus,health
  health:
    redis:
      enabled: off

# flowable
flowable:
  custom-mybatis-mappers:
  eventregistry:
    enabled: false
  idm:
    enabled: false


# logging
logging.level:
  org.springframework.security: DEBUG
