spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  datasource:
    username: sa
    url: jdbc:h2:file:./keycloak;AUTO_SERVER=TRUE;NON_KEYWORDS=VALUE

keycloak:
  server:
    context-path: /auth
    username: admin
    password: admin
    context-redirect: true

logging:
  level:
    root: ERROR