networks:
  devops-test:
    external: true

services:
  consul:
    container_name: consul
    image: bitnami/consul:1.20.2
    networks:
      - devops-test
    environment:
      CONSUL_DATACENTER: N100_DC
    volumes:
      - ./conf/consul.json:/opt/bitnami/consul/conf/consul.json
    ports:
      - '8300:8300' # rpc
      - '8301:8301' # lan gossip
      - '8301:8301/udp' #lan gossip
      - '8302:8302' # wan gossip
      - '8302:8302/udp' #wan gossip
      - '8500:8500' # http
      - '8600:8600' # dns
      - '8600:8600/udp' # dns