server:
  port: 8082

spring:
  application:
    name: oauth2login

  security:
    oauth2:
      client:
        provider:
          pooi-keycloak:
            issuer-uri: https://keycloak.pooi.app/realms/pooi
        registration:
          keycloak:
            provider: pooi-keycloak
            authorization-grant-type: authorization_code
            client-id: workflow_app
            client-secret: 9eWHLiBnx82glZ8XPXou1glaoKuoPvnN
            scope: openid

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true