server:
  port: 0

# discover
spring.cloud.consul:
  host: consul.pooi.app
  port: 443
  scheme: https
  discovery:
    enabled: true
    register: false
    instanceId: ${spring.application.name}:${random.value} # ${spring.application.name}:${profiles separated by comma}:${server.port}”
    prefer-ip-address: true
    # healthCheckPath: /my-health-check
    healthCheckInterval: 10s

grpc:
  client:
    pooi-workflow-core:
      address: 'discovery:///pooi-workflow-core'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext