server:
  port: 8081

# discover
spring.cloud.consul:
  host: consul.pooi.app
  port: 443
  scheme: https
  discovery:
    enabled: true
    instanceId: ${spring.application.name}:${random.value} # ${spring.application.name}:${profiles separated by comma}:${server.port}”
    prefer-ip-address: true
    ip-address: 192.168.31.122
    # healthCheckPath: /my-health-check
    healthCheckInterval: 10s
    tags:
      - "grpc"
    metadata:
      grpc-port: ${grpc.server.port}

grpc:
  client:
    pooi-workflow-core:
      address: 'discovery:///pooi-workflow-core'
      negotiation-type: plaintext